windows: require Windows 8+
../../libfwupdplugin/fu-windows-efivars.c:31:14: error: implicit declaration of function 'GetFirmwareType'; did you mean 'GetFileType'? [-Wimplicit-function-declaration]
   31 |         if (!GetFirmwareType(&firmware_type)) {
      |              ^~~~~~~~~~~~~~~
      |              GetFileType

Signed-off-by: Daniel Schaefer <dhs@frame.work>