freebsd: Depend on libinotify
It's treated like a userspace library with pkgconf .pc file in order to link to it.

Fixes:

```
/usr/local/bin/ld: src/libfwupdengine.so.p/fu-remote-list.c.o: in function `fu_remote_list_fixup_inotify_error':
/home/runner/work/fwupd/fwupd/venv/build/../../src/fu-remote-list.c:117:(.text+0x92c): undefined reference to `inotify_init'
/usr/local/bin/ld: /home/runner/work/fwupd/fwupd/venv/build/../../src/fu-remote-list.c:124:(.text+0x96c): undefined reference to `inotify_add_watch'
/usr/local/bin/ld: /home/runner/work/fwupd/fwupd/venv/build/../../src/fu-remote-list.c:132:(.text+0x9b1): undefined reference to `inotify_rm_watch'
collect2: error: ld returned 1 exit status
```

Signed-off-by: Daniel Schaefer <dhs@frame.work>